### ISSUE TITLE
Texture of slashblade appears black on 1.20.1-0.1.2

### ISSUE THREAD

**Issue by xgugugu** [flammpfeil/SlashBlade_2#60]
Like this:

![图片](https://github.com/flammpfeil/SlashBlade_2/assets/85472190/1ec2d525-79bf-4d26-b1a5-75e48cf0fa94)

Mod version: 1.20.1-0.1.2

NeoForge version: 47.1.104

OS: Manjaro, Linux Kernel 6.6.26

Desktop: GNOME 45 on Wayland

Graphics: AMD Radeon Vega 8 Graphics

Java version:

```
openjdk version "21.0.2" 2024-01-16
OpenJDK Runtime Environment (build 21.0.2+13)
OpenJDK 64-Bit Server VM (build 21.0.2+13, mixed mode, sharing)
```

OpenGL version:

```
OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.2-manjaro1.1
```

Logs:

```
[18:32:40] [Worker-Main-2/ERROR] [minecraft/ModelManager]: Failed to load model slashblade:models/item/slashblade.json
com.google.gson.JsonSyntaxException: Expected slashblade:user to be a Float, was "exists"
	at net.minecraft.util.GsonHelper.m_13888_(GsonHelper.java:221) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.block.model.ItemOverride$Deserializer.m_173450_(ItemOverride.java:53) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.renderer.block.model.ItemOverride$Deserializer.deserialize(ItemOverride.java:41) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.renderer.block.model.ItemOverride$Deserializer.deserialize(ItemOverride.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2395!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2395!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2395!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2395!/:?] {}
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2395!/:?] {}
	at net.minecraft.client.renderer.block.model.BlockModel$Deserializer.m_111494_(BlockModel.java:329) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.model.BlockModel$Deserializer.deserialize(BlockModel.java:315) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.model.ExtendedBlockModelDeserializer.deserialize(ExtendedBlockModelDeserializer.java:53) ~[forge-1.20.1-47.1.104-universal.jar%23183!/:?] {re:classloading}
	at net.minecraftforge.client.model.ExtendedBlockModelDeserializer.deserialize(ExtendedBlockModelDeserializer.java:38) ~[forge-1.20.1-47.1.104-universal.jar%23183!/:?] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2395!/:?] {}
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:524) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.block.model.BlockModel.m_111461_(BlockModel.java:74) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_246478_(ModelManager.java:110) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
[18:32:40] [Worker-Main-2/WARN] [minecraft/ModelBakery]: Unable to load model: 'slashblade:slashblade#inventory' referenced from: slashblade:slashblade#inventory: java.io.FileNotFoundException: slashblade:models/item/slashblade.json
```

**Comment by THMonster** [comment]
I got the same problem. kde6 wayland with AMD 680m
